# Generated by Django 5.1.1 on 2024-10-01 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Telecaller', 'Telecaller')], max_length=30, null=True),
        ),
    ]
