# Generated by Django 5.1.1 on 2024-10-01 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='notification_token',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
