# Generated by Django 5.1.1 on 2024-09-12 02:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=15)),
                ('lead_source', models.IntegerField(choices=[(1, 'Source 1'), (2, 'Source 2')])),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('profession', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('qualification', models.CharField(max_length=255)),
                ('annual_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_of_birth', models.DateField()),
                ('lead_status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('converted', 'Converted'), ('lost', 'Lost')], default='new', max_length=10)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
