# Generated by Django 5.1.1 on 2024-10-02 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_status',
            field=models.CharField(choices=[('Fresh', 'Fresh'), ('Follow Up', 'Follow Up'), ('Won', 'Won'), ('Re-Enquired', 'Re-Enquired'), ('Closed', 'Closed')], default='Fresh', max_length=14),
        ),
    ]
