# Generated by Django 5.1.1 on 2024-10-02 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0002_alter_lead_gender_alter_lead_lead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='center_name',
            field=models.CharField(choices=[('B2B', 'B2B'), ('Pune', 'Pune')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lead',
            name='annual_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_source',
            field=models.IntegerField(blank=True, choices=[(1, 'Source 1'), (2, 'Source 2')], null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='profession',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='qualification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
