# Generated by Django 5.1.1 on 2024-10-02 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0003_lead_center_name_alter_lead_annual_income_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='contact_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
