# Generated by Django 5.1.1 on 2024-12-16 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0005_lead_assined'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='assined',
            new_name='assigned',
        ),
    ]
