# Generated by Django 5.1.1 on 2025-04-17 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0008_lead_organization'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallLogs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('call_type', models.IntegerField(choices=[(1, 'Incoming'), (2, 'Outgoing'), (3, 'Missed')])),
                ('called_time', models.DateTimeField()),
                ('call_duration', models.IntegerField(help_text='Duration in seconds')),
                ('lead_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='lead.lead')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to='organizations.organization')),
            ],
        ),
    ]
