# Generated by Django 5.1.1 on 2025-04-17 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0009_calllogs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='center_name',
        ),
    ]
