# Generated by Django 5.1.1 on 2025-04-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0010_remove_lead_center_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='lead_source',
            field=models.IntegerField(blank=True, choices=[('Source 1', 'Source 1'), ('Source 1', 'Source 2')], null=True),
        ),
    ]
