# Generated by Django 5.1.1 on 2025-04-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0012_leadsource_alter_lead_lead_source_leadstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadstatus',
            name='name_alias',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='leadsource',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='leadstatus',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
